name: Android develop CI

on:
  push:
    branches: [ "feature_github_action" ]
  pull_request:
    branches: [ "feature_github_action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for scripts
        run: |
          chmod +x copy-hmoa-android-secrets.sh

      - name: Run copy google-service.json
        run: ./copy-hmoa-android-secrets.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build