name: Android develop CI

on:
  pull_request:
    branches:
      - "develop"
      - "release"
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HMOA_ANDROID_SECRET_TOKEN: ${{secrets.HMOA_ANDROID_SECRET_TOKEN}}
      RELEASE_KEYSTORE: ${{secrets.RELEASE_KEYSTORE}}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for scripts
        run: |
          chmod +x copy-hmoa-android-secrets.sh

      - name: Generate release.keystore
        run: echo '${{ secrets.RELEASE_KEYSTORE }}' | base64 --d > ./app/release.keystore

      - name: Run copy secrets
        run: ./copy-hmoa-android-secrets.sh

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build for debug with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release