name: Android develop CD

on:
  push:
    branches:
      - release

jobs:
  cd:

    runs-on: ubuntu-latest
    env:
      HMOA_ANDROID_SECRET_TOKEN: ${{secrets.HMOA_ANDROID_SECRET_TOKEN}}
      RELEASE_KEYSTORE: ${{secrets.RELEASE_KEYSTORE}}
      KEY_ALIAS: ${{secrets.KEY_ALIAS}}
      KEY_STORE_PASSWORD: ${{KEY_STORE_PASSWORD}}
      KEY_PASSWORD: ${{KEY_PASSWORD}}
      SERVICE_ACCOUNT_JSON: ${{ SERVICE_ACCOUNT_JSON }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/workflows/setup-jdk.yml

      - name: Grant execute permissions for scripts
        run: |
          chmod +x copy-hmoa-android-secrets.sh

      - name: Generate release.keystore
        run: echo '${{ secrets.RELEASE_KEYSTORE }}' | base64 --d > ./app/release.keystore

      - name: Run copy secrets
        run: ./copy-hmoa-android-secrets.sh

      - name: Gradle Caching
        uses: ./.github/workflows/gradleCaching.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release AAB
        run: ./gradlew bundleRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.hmoa.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: ./.github/workflows/whatsnew-ko-KR.txt