name: Android develop CI

on:
  pull_request:
    branches:
      - "feature/hbti"
      - "release"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HMOA_ANDROID_SECRET_TOKEN: ${{secrets.HMOA_ANDROID_SECRET_TOKEN}}
      RELEASE_KEYSTORE: ${{secrets.RELEASE_KEYSTORE}}
    steps:
      - name: Grant execute permissions for scripts
        run: |
          chmod +x ./copy-hmoa-android-secrets.sh

      - name: Generate release.keystore
        run: echo '${{ secrets.RELEASE_KEYSTORE }}' | base64 --d > ./app/release.keystore

      - name: Run copy secrets
        run: ./copy-hmoa-android-secrets.sh

      - name: Gradle Caching
        uses: ./.github/workflows/gradleCaching.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build for debug with Gradle
        run: ./gradlew assembleDebug
